version: "3"
networks:
  network:
    driver: bridge
services:
  php:
    build:
      context: .docker
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9000:9000"
    environment:
      PATH: "/root/.composer/vendor/bin:${PATH}"
    networks:
      - network
  pgsql:
    image: postgres:9.6-alpine
    restart: always
    container_name: pgsql
    ports:
      - 5433:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tests
      POSTGRES_USER: tests
      POSTGRES_DB: tests
    networks:
      - network
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6382:6379"
    networks:
      - network
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/log:/var/log/nginx/
    depends_on:
      - php
      - pgsql
      - redis
    networks:
      - network
volumes:
  data: